POM: update dependency versions
* imagej-mesh: 0.2.1-SNAPSHOT -> 0.3.0
* scenery: 0.2.4-SNAPSHOT -> 0.3.0-SNAPSHOT
* cleargl: 2.1.1 -> 2.1.3
* joml: 1.9.8-SNAPSHOT -> 1.9.8

This resolves NoSuchMethodError in ClearGL upon startup,
due to version skew.

But SciView still displays nothing in the scene.